version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    links:
      - postgres 
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'adgnOl72VEspIwcZh'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}

